export const initialData = {
    tasks: [{
        id: "task-1",
        name: "Get Fruits for kids",
        category: "domestic",
        column: "on_the_mark",
        territory: "domestic",
        priority: "urgent",
        photos: [
            "https://images.pexels.com/photos/1630588/pexels-photo-1630588.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/51312/kiwi-fruit-vitamins-healthy-eating-51312.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/1128678/pexels-photo-1128678.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        ],
        amount: 1400,
        time: 60,
    }, 
    {
        id: "task-2",
        name: "Solve unresponsive issue in Villo",
        category: "work",
        column: "inception",
        territory: "central_america",
        priority: "normal",
        photos: [
            "https://images.pexels.com/photos/2804282/pexels-photo-2804282.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/4550985/pexels-photo-4550985.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/2100063/pexels-photo-2100063.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        ],
        amount: 1400,
        time: 60,
    },
    {
        id: "task-3",
        name: "Get Fruits for kids",
        category: "domestic",
        column: "on_the_mark",
        territory: "domestic",
        priority: "urgent",
        photos: [
            "https://images.pexels.com/photos/4109267/pexels-photo-4109267.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
            ],
        amount: 36000,
        time: 360,
    },
    {
        id: "task-4",
        name: "Secure Visa for England",
        category: "international",
        column: "on_the_mark",
        territory: "europe",
        priority: "urgent",
        photos: [
            "https://images.pexels.com/photos/4921516/pexels-photo-4921516.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/4922080/pexels-photo-4922080.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        ],
        amount: 700,
        time: 120,
    },
    {
        id: "task-5",
        name: "Get Important Books",
        category: "personal",
        column: "on_the_mark",
        territory: "south_east_asia",
        priority: "high",
        photos: [
            "https://images.pexels.com/photos/4921516/pexels-photo-4921516.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/4922080/pexels-photo-4922080.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        ],
        amount: 700,
        time: 120,
    },
    {
        id: "task-6",
        name: "Misceleneous works to be done",
        category: "misc",
        column: "in_progress",
        territory: "central_america",
        priority: "high",
        photos: [
            "https://images.pexels.com/photos/4921516/pexels-photo-4921516.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/4922080/pexels-photo-4922080.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        ],
        amount: 700,
        time: 120,
    },
    {
        id: "task-7",
        name: "Get Fruits for kids",
        category: "domestic",
        column: "on_the_mark",
        territory: "domestic",
        priority: "urgent",
        photos: [
            "https://images.pexels.com/photos/1630588/pexels-photo-1630588.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/51312/kiwi-fruit-vitamins-healthy-eating-51312.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/1128678/pexels-photo-1128678.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        ],
        amount: 1400,
        time: 60,
    }, 
    {
        id: "task-8",
        name: "Solve unresponsive issue in Villo",
        category: "work",
        column: "inception",
        territory: "central_america",
        priority: "normal",
        photos: [
            "https://images.pexels.com/photos/2804282/pexels-photo-2804282.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/4550985/pexels-photo-4550985.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/2100063/pexels-photo-2100063.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        ],
        amount: 1400,
        time: 60,
    },
    {
        id: "task-9",
        name: "Get Fruits for kids",
        category: "domestic",
        column: "on_the_mark",
        territory: "domestic",
        priority: "urgent",
        photos: [
            "https://images.pexels.com/photos/4109267/pexels-photo-4109267.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
            ],
        amount: 36000,
        time: 360,
    },
    {
        id: "task-10",
        name: "Secure Visa for England",
        category: "international",
        column: "on_the_mark",
        territory: "europe",
        priority: "urgent",
        photos: [
            "https://images.pexels.com/photos/4921516/pexels-photo-4921516.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/4922080/pexels-photo-4922080.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        ],
        amount: 700,
        time: 120,
    },
    {
        id: "task-11",
        name: "Get Important Books",
        category: "personal",
        column: "on_the_mark",
        territory: "south_east_asia",
        priority: "high",
        photos: [
            "https://images.pexels.com/photos/4921516/pexels-photo-4921516.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/4922080/pexels-photo-4922080.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        ],
        amount: 700,
        time: 120,
    },
    {
        id: "task-12",
        name: "Misceleneous works to be done",
        category: "misc",
        column: "in_progress",
        territory: "central_america",
        priority: "high",
        photos: [
            "https://images.pexels.com/photos/4921516/pexels-photo-4921516.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/4922080/pexels-photo-4922080.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        ],
        amount: 700,
        time: 120,
    },
    {
        id: "task-13",
        name: "Get Fruits for kids",
        category: "domestic",
        column: "on_the_mark",
        territory: "domestic",
        priority: "urgent",
        photos: [
            "https://images.pexels.com/photos/1630588/pexels-photo-1630588.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/51312/kiwi-fruit-vitamins-healthy-eating-51312.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/1128678/pexels-photo-1128678.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        ],
        amount: 1400,
        time: 60,
    }, 
    {
        id: "task-14",
        name: "Solve unresponsive issue in Villo",
        category: "work",
        column: "inception",
        territory: "central_america",
        priority: "normal",
        photos: [
            "https://images.pexels.com/photos/2804282/pexels-photo-2804282.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/4550985/pexels-photo-4550985.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/2100063/pexels-photo-2100063.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        ],
        amount: 1400,
        time: 60,
    },
    {
        id: "task-15",
        name: "Get Fruits for kids",
        category: "domestic",
        column: "on_the_mark",
        territory: "domestic",
        priority: "urgent",
        photos: [
            "https://images.pexels.com/photos/4109267/pexels-photo-4109267.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
            ],
        amount: 36000,
        time: 360,
    },
    {
        id: "task-16",
        name: "Secure Visa for England",
        category: "international",
        column: "on_the_mark",
        territory: "europe",
        priority: "urgent",
        photos: [
            "https://images.pexels.com/photos/4921516/pexels-photo-4921516.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/4922080/pexels-photo-4922080.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        ],
        amount: 700,
        time: 120,
    },
    {
        id: "task-17",
        name: "Get Important Books",
        category: "personal",
        column: "on_the_mark",
        territory: "south_east_asia",
        priority: "high",
        photos: [
            "https://images.pexels.com/photos/4921516/pexels-photo-4921516.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/4922080/pexels-photo-4922080.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        ],
        amount: 700,
        time: 120,
    },
    {
        id: "task-18",
        name: "Misceleneous works to be done",
        category: "misc",
        column: "in_progress",
        territory: "central_america",
        priority: "high",
        photos: [
            "https://images.pexels.com/photos/4921516/pexels-photo-4921516.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            "https://images.pexels.com/photos/4922080/pexels-photo-4922080.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        ],
        amount: 700,
        time: 120,
    },
]
}

export const categories = [
    {id: "domestic", value: "Domestic"},
    {id: "work", value: "Work"},
    {id: "international",value: "International"},
    {id: "personal", value: "Personal"},
    {id: "misc", value: "Misceleneous"},
]

export const columns = [
    {id: "on_the_mark", value: "No Stage"}, 
    {id: "inception", value: "Introduction Stage"},
    {id: "in_progress", value: "In Progress"},
    {id: "work_done", value: "Work Done"},
    {id: "submitted", value: "Submitted"},
    {id: "cancelled", value: "Cancelled"},
]

export const territories = [
    {id: "domestic", value: "Domestic"},
    {id: "central_america", value: "Central America"},
    {id: "europe", value: "Europe"},
    {id: "south_east_asia", value: "South East Asia"},
]

export const priorities = [
    {id: "unassigned", value: "Unassigned"},
    {id: "low", value: "Low"},
    {id: "normal", value: "Normal"},
    {id: "high", value: "High"},
    {id: "urgent", value: "Urgent"},
]